{% set name = "graphene-mongo" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/graphene_mongo-{{ version }}.tar.gz
  sha256: aab35d29032228f2cbc22048e462ab43b356f5f1724ae17f0295be048b0bda3a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }},<4.0
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - graphene >=3.1.1
    - graphene-federation >=3.1.5
    - promise >=2.3
    - mongoengine >=0.27
    - asgiref >=3.7.2,<4.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - graphene_mongo

about:
  summary: Graphene Mongoengine integration
  home: https://github.com/graphql-python/graphene-mongo
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - KingDarBoja
