{% set name = "graphene-mongo" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54da09ab45880e118ac1be1a059dc23cbb3e1398e1a696c808abb2a2c463645b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - graphene >=3.1.1
    - graphene-federation >=3.1.5
    - promise >=2.3
    - mongoengine >=0.27
    - asgiref >=3.7.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - graphene_mongo

about:
  home: https://github.com/graphql-python/graphene-mongo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Graphene Mongoengine integration
  doc_url: https://graphene-mongo.readthedocs.io/en/latest/
  dev_url: https://github.com/graphql-python/graphene-mongo
  description: A Mongoengine integration for Graphene.

extra:
  recipe-maintainers:
    - KingDarBoja
