{% set name = "graphene-mongo" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/graphene_mongo-{{ version }}.tar.gz
  sha256: 54da09ab45880e118ac1be1a059dc23cbb3e1398e1a696c808abb2a2c463645b
https://files.pythonhosted.org/packages/57/3f/9df8f5a678a3758dee9123e14ce6938912951634cd65d6626ce10f27620f/graphene_mongo-0.4.4.tar.gz
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }},<4.0
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - graphene >=3.1.1
    - graphene-federation >=3.1.5
    - promise >=2.3
    - mongoengine >=0.27
    - asgiref >=3.7.2,<4.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - graphene_mongo

about:
  summary: Graphene Mongoengine integration
  home: https://github.com/graphql-python/graphene-mongo
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - KingDarBoja