{% set name = "graphene-mongo" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0fa9542a4bdc80890d407a9a495838209b4b4f60c21528966f534cc894d94b27

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - graphene >=2.1.3,<3
    - iso8601 >=0.1.12
    - mongoengine >=0.15.0
    - python
    - singledispatch >=3.4.0.3

test:
  imports:
    - graphene_mongo

about:
  home: https://github.com/graphql-python/graphene-mongo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Graphene Mongoengine integration
  doc_url: https://graphene-mongo.readthedocs.io/en/latest/
  dev_url: https://github.com/graphql-python/graphene-mongo
  description: A Mongoengine integration for Graphene.

extra:
  recipe-maintainers:
    - KingDarBoja
