{% set name = "graphene-mongo" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 83a9380bc0121fcefe9358155ef6b1e778b0673027e4fa78364a9366ae6ee92b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - graphene >=2.1.3,<3
    - iso8601 >=0.1.12
    - mongoengine >=0.15.0
    - python
    - singledispatch >=3.4.0.3

test:
  imports:
    - graphene_mongo

about:
  home: https://github.com/graphql-python/graphene-mongo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Graphene Mongoengine integration
  doc_url: https://graphene-mongo.readthedocs.io/en/latest/
  dev_url: https://github.com/graphql-python/graphene-mongo
  description: A Mongoengine integration for Graphene.

extra:
  recipe-maintainers:
    - KingDarBoja
